### PR TITLE
Respawn cone_detector

### PR DESCRIPTION
**Pull request by griswaldbrooks**
Set respawn=true to cone_detector.launch and republishing the android image as compressed to allow image_view to see it.

### CODE REVIEW

**Review by mwimble — APPROVED** [review]
Not sure why you call it android image, but otherwise looks good

**Comment by griswaldbrooks** [comment]
I don't know why it's called that either, other than @jrcapriles had named it originally, which was motivated by the android app. We could call it something else.
`mobile_app_`*

**Comment by mwimble** [comment]
Sorry, I was thinking this was the camera topic name. I don’t know if we’ve tried this with iOS yet, so I don’t know if it’s android specific. Not an issue for me, yet.

**Comment by griswaldbrooks** [comment]
I don't know if there is an iphone app.

**Pull request merged**
